---
tasks:
- name: buildings
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        DISPLAY=":$XVNC_PORT" bundle exec cucumber -p default --strict "engines/leihs_admin/features/buildings.feature"
- name: database
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        DISPLAY=":$XVNC_PORT" bundle exec cucumber -p default --strict "engines/leihs_admin/features/database.feature"
- name: delegation
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        DISPLAY=":$XVNC_PORT" bundle exec cucumber -p default --strict "engines/leihs_admin/features/delegation.feature"
- name: inventory_csv
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        DISPLAY=":$XVNC_PORT" bundle exec cucumber -p default --strict "engines/leihs_admin/features/inventory_csv.feature"
- name: inventory_pools
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        DISPLAY=":$XVNC_PORT" bundle exec cucumber -p default --strict "engines/leihs_admin/features/inventory_pools.feature"
- name: settings
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        DISPLAY=":$XVNC_PORT" bundle exec cucumber -p default --strict "engines/leihs_admin/features/settings.feature"
- name: statistik
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        DISPLAY=":$XVNC_PORT" bundle exec cucumber -p default --strict "engines/leihs_admin/features/statistik.feature"
- name: suppliers
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        DISPLAY=":$XVNC_PORT" bundle exec cucumber -p default --strict "engines/leihs_admin/features/suppliers.feature"
- name: users
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        DISPLAY=":$XVNC_PORT" bundle exec cucumber -p default --strict "engines/leihs_admin/features/users.feature"
- name: wartungsmodus
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        DISPLAY=":$XVNC_PORT" bundle exec cucumber -p default --strict "engines/leihs_admin/features/wartungsmodus.feature"
