---
- name: Install packages necessary for Rails hosting
  apt: pkg={{ item }} state=present
  sudo: True
  with_items:
    - apache2
    - apache2-threaded-dev
    - autoconf
    - automake
    - bison
    - build-essential
    - curl
    - git
    - libapr1-dev
    - libcurl4-openssl-dev
    - libffi-dev
    - libgdbm-dev
    - libncurses5-dev
    - libssl-dev
    - libreadline6-dev
    - libtool
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - make
  tags:
    - packages

- name: register ruby version variable
  command: bash -lc 'rvm current'
  register: ruby_version

- name: install mod_passenger
  command: bash -lc 'gem install passenger'

- name: build mod_passenger for apache
  command: bash -lc 'passenger-config --compiled'
  register: result
  ignore_errors: True
- command: bash -lc 'passenger-install-apache2-module -a'
  when: result|failed

- name: configure apache for mod_passenger (get snippet)
  command: bash -lc 'passenger-install-apache2-module --snippet > /tmp/passenger.load'

- name: configure apache for mod_passenger (copy snippet)
  sudo: True
  command: cp /tmp/passenger.load /etc/apache2/mods-available/passenger.load

- name: Enable Passenger module
  sudo: True
  command: a2enmod passenger
  notify:
  - restart apache
