releases:

### CURRENT #######################################################################

- version_major: 4
  version_minor: 4
  version_patch: 0
  version_pre: RC.1

### HISTORY  ######################################################################

- version_major: 4
  version_minor: 3
  version_patch: 1
  version_pre: null
  description: |

    ### Frontend Bug Fixes

    - Fix: BarcodeScanner: don't operate on focused inputs
    - Fix: upgrade tooltipster jquery plugin

- version_major: 4
  version_minor: 3
  version_patch: 0
  version_pre: null
  description: |

    - Feature: deactive pools (resolves #223)
    - Fix: Forbid first admin user if already exists
    - Fix: Inventory search in location's room (resolves #221)

- version_major: 4
  version_minor: 2
  version_patch: 0
  version_pre: null
  description: |

    ### Inventory Feature and Bug Fixing

    **Manage section**
    - When copying an item, the field "last checked" on the new item is set to the current date

    **Borrow section**
    - The information in the links **order**, **hand over** and **returns** on the top of the page show on the right hand side of the page the **date from** and **date to**. Before we showed the dates until or since as f.e. 1970 days since 23.7.2014.
    - The error messages on the top of the page when sending an order were not shown correctly.

- version_major: 4
  version_minor: 1
  version_patch: 0
  version_pre: null
  description: |

    ### Adjustments and Bug Fixing

    **Missing translations**
    - When submitting an order in the borrow section in the German part, the success message has now been translated to German.
    - Tab "return" in German part of leihs has now been translated to German

    **Borrow section**
    - The filter settings are not deleted anymore when switching from one category to another

    **Lending section**
    - Feature delegation contracts: When searching for a user, not only his own contracts are shown in the overview but also contracts of delegations, where this user is acting as borrower.
    - Bug fixing: Adding an item or model is not case sensitive anymore. This bug was introduced with the PostgreSQL-Update
    - Bug fixing: It is not possible to lend the same item at the same time to the same user.
    - Bug fixing: Date field when editing the calender in the return page was buggy. Now it is possible to delete the date or type a new date

    **Manage section**
    - Feature duplicate items: If you save an item where the serial-nr. already exists in leihs, you receive a warning asking, if you really want to save. This should help keep your inventory "tidy".

    **Admin section**
    - The shown time in the Audits-Page has been corrected to show the current time
    - The newest entries in the Audits-Page are now shown on the top

    **Installing leihs V4**
    - Enabling LDAP  in V4: How-to-documentation adjusted to enable LDAP under PostgreSQL
    - We now provide the possibility to create the first leihs-Admin-user through a UI
