---
- hosts: vagrant
  user: vagrant
  sudo: True
  tasks:
  - name: Add GPG key for MariaDB packages
    apt_key: id=1BB943DB url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xCBCB082A1BB943DB state=present
  - name: Add the MariaDB repository
    apt_repository: repo='deb http://mirror.netcologne.de/mariadb/repo/5.5/debian wheezy main' state=present
  - name: Install MariaDB server
    apt: pkg=mariadb-server state=installed update_cache=true
  - name: Install MariaDB client
    apt: pkg=mariadb-client state=installed update_cache=true
  - name: Install MariaDB client library (dev packages)
    apt: pkg=libmariadbclient-dev state=installed update_cache=true
  - name: Install MariaDB client library
    apt: pkg=libmariadbclient18 state=installed update_cache=true
