---
- hosts: vagrant
  user: vagrant
  sudo: True
  tasks:
  - name: Install requirements for managing repos via Ansible
    apt: pkg=python-apt state=installed
  - name: Install requirements for managing repos via Ansible
    apt: pkg=python-pycurl state=installed
